{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-service.dbSecretName" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
{{- end }} 